name: Run Python Script

on: 
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have dependencies in a requirements.txt
    - name: Run Python script
      run: |
        python trajectory.py  # Replace with your file name
